### PR TITLE
use subproject/pkg-config dependency for nlohmann_json

### PR DESCRIPTION
**Pull request by eli-schwartz**

### CODE REVIEW

**Comment by falconindy** [comment]
History would show that this used to be a thing. I got rid of it because it's an AUR dep, and if it isn't installed, the subproject clone is enormous. Packaging the headers along side the project seemed to be a good compromise.

**Comment by eli-schwartz** [comment]
Getting rid of 20K lines of vendored code would also be nice, but there doesn't seem to be a good solution to using this as a subproject. Sadly, meson's wrapdb which does have nlohmann_json, has a really inferior one: it is both out of date and tries to install_subdir() in a *subproject*.

I've submitted https://github.com/nlohmann/json/issues/1672 asking for an upstream wrap-friendly download.

**Comment by falconindy** [comment]
Thanks for raising this with upstream. I'll be out of town until the end of the month. Maybe by the time I'm back things will have improved here.

**Comment by eli-schwartz** [comment]
The latest version of nlohmann_json provides a self-contained wrappable include.zip, so I've updated the PR to use this.

```
$ meson builddir --wrap-mode forcefallback >/dev/null 2>&1 && du -sh subprojects/packagecache/nlohmann_json-3.7.1.zip
276K	subprojects/packagecache/nlohmann_json-3.7.1.zip
```

**Comment by falconindy** [comment]
Thanks! Merged manually to fixup some ordering nitpicks.

**Pull request closed without merging**
