### PR TITLE
WIP: Add a change directory flag for downloads

### PR DESCRIPTION
**Pull request by wasamasa**
This adds a flag in the spirit of the `-C` option as seen in `tar`. Setting it will change the current directory before downloading packages.

This is marked as WIP because the wrong directory is printed after the download is complete, namely the one we started in, with the package base name appended. From what I can tell it happens because the corresponding class is initialized with the current directory in a member and that member is accessed. Is there a reason for this pattern instead of just printing the current directory when needed?

edit: Also, how do you prefer the new option to be printed? This is the first time there's a short and long option with a required argument, so listing it twice could work.

edit: I discovered https://en.cppreference.com/w/cpp/filesystem is a thing. Using it might make the code clearer, but this is using exceptions while the rest of the codebase uses integer error codes.

### CODE REVIEW

**Comment by falconindy** [comment]
I'd get rid of the pwd_ member on the Auracle class and just keep it local within Download(). That's the only place it's ever referenced,

I guess I'm looking forward to the filesystem lib (aside from the ridiculous operator/ overload), but it isn't yet fully available in libstdc++.

I'm also being told that recent env(1) has a -C flag, so you could just:

```env -C /somewhere/else auracle download ...```

**Comment by wasamasa** [comment]
Alright, I've addressed these. `env -C` is an option for me, the reason I wrote this is because the only thing I'm missing from cower is some way to specify a target directory everything lands in. With cower I solved this with a config file (way beyond me to implement that in C++), but an environment variable or option would work for me as well. I imagine I'm not the only one, hence why I submitted this PR. If the official solution is to delegate it to `env -C`, fine by me.

**Comment by falconindy** [comment]
Thanks, there's still a few problems with the PR.

- getcwd allocates memory, so you're leaking memory on every download (probably not critical).
- there's no check to ensure that the target directory is writeable. That's ok, the check needs to exist even without the new -C flag (e.g. for when you invoke auracle in /usr as non-root).
- if you validate up front that your value for -C is non-empty, then you avoid the need for the std::optional.
- missing: updates to manpage and bash completion.

I eventually found a reference buried in GCC docs about c++17 that suggests that you need to link with `-lstdc++fs` to use the new filesystem header. That seems to work, and it's vaguely nicer than what libc offers.

I've got this all working on my local branch. I'll credit you in the commit.

**Comment by wasamasa** [comment]
Cool, thank you.

**Pull request closed without merging**
